name: Download and Split Android Commandline Tools

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download_and_split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download commandline tools
        run: |
          mkdir -p tools
          curl -L "https://dl.google.com/android/repository/commandlinetools-win-13114758_latest.zip" -o tools/commandlinetools.zip

      - name: Remove old split files
        run: |
          rm -f tools/commandlinetools.zip.part-* || true

      - name: Split zip file into 50MB chunks
        run: |
          cd tools
          split -b 50M commandlinetools.zip commandlinetools.zip.part-
          rm commandlinetools.zip
          cd ..

      - name: Commit and push split files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add tools/
          git commit -m "Update split commandlinetools files"
          git push
